### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by subaru22b** [retorquere/zotero-thebrain-export#2]
Hello retorquere,

I tested the zotero-thebrain-export but the export failed in zotero.

Using zotero 5.0.60 portable version

I added it to the translator folder

Highlighted a book

Go to file, export Library, 

Error
An error occurred while trying to export the selected file

also tried right clicking export item but the same Error

An error occurred while trying to export the selected file

What could be the problem?

**Comment by retorquere** [comment]
Try 0.0.16 -- the exporter failed on non-synced items.

**Comment by subaru22b** [comment]
version 0.0.16 solved it! Thank you!
