### ISSUE TITLE
Zotero links back to Zotero Quick Start Guide

### ISSUE THREAD

**Issue by subaru22b** [retorquere/zotero-thebrain-export#3]
Hello,

I'm using zotero 5.0.60 with plugins Zotfile and Zutilo

The Brain.js export creates an zotero link attachment ((zotero://select/item/0_MK874KTG), when you clicked on the zotero link, it will go to Zotero Quick Start Guide entry, instead of the book linked to it. 

Further testing I found out that if the zotero link has /items/ instead of /item/ it will open to the right linked book.

zotero://select/**item**/0_MK874KTG - goes to Zotero Quick Start Guide
zotero://select/**items**/0_MK874KTG - goes to the right linked book

Thank you!

**Comment by subaru22b** [comment]
I found the code line 138 should be
        detail(`zotero://select/items/${ug === 'users/local' ? '0' : libraryID}_${key}`, '+');

**Comment by retorquere** [comment]
0.0.17 has the fix.
